### ISSUE TITLE
Can't edit world

### ISSUE THREAD

**Issue by DartPower** [Bertware/bukkitgui#2]
On 2.0 version (2.0.0.215)
But on old v1 is fully tested working (1.7.4.538)

Can't edit & use world on new version.

Just replaced exe and launched server.
Downgraded to 1.7.4.538 and problem solved

**Comment by simon816** [comment]
Isn't this an issue for [bukkitgui2](https://github.com/Bertware/bukkitgui2)?

**Comment by Bertware** [comment]
This is indeed an issue for bukkitgui2. It looks like there's an issue in your server config (minecraft .yml files)
