### ISSUE TITLE
Pls pls pls pls Help me I cant Start the Server

### ISSUE THREAD

**Issue by Guintz56** [Bertware/bukkitgui#5]
![untitled](https://cloud.githubusercontent.com/assets/24538780/21129511/e1566928-c13c-11e6-9a37-93e5cbaabe4f.png)
How To Fix This ??? Pls Help me

**Comment by Bertware** [comment]
* Try putting your maximum ram to a value below 1500.
* Try changing the java installation (java version) being used.
* Try changing the server type.
